### ISSUE TITLE
Consider optimizing ntz=0

### ISSUE THREAD

**Issue by klauspost** [ronanh/intcomp#3]
A lot of the packing/unpacking code has variable shifts for ntz. These are relatively expensive on Intel.

However, it is quite likely that `ntz==0`, so I suggest you generate a version of your code that omits these.

**Comment by ronanh** [comment]
@klauspost I have tried, the optimisation you suggested.
Quite a lot of code gets generated!

In the end, it's about 10% faster in the case ntz=0

**Comment by klauspost** [comment]
I don't know if it makes sense to split it into separate files. Goland is already choking on the 60KLOC file. :)

I can't really make the decision it if makes sense to include, though 10% is a nice bonus.

**Comment by ronanh** [comment]
VSCode is better big files, unless it's full of syntax errors...
I can generate code by type, should be more manageable.
